// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: ecommerce/order/order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	product "grpc-course-protobuf/pb/ecommerce/product"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Products      []*product.Product     `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_ecommerce_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_ecommerce_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Order) GetProducts() []*product.Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_ecommerce_order_order_proto protoreflect.FileDescriptor

const file_ecommerce_order_order_proto_rawDesc = "" +
	"\n" +
	"\x1becommerce/order/order.proto\x12\x0fecommerce.order\x1a\x1fecommerce/product/product.proto\"g\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x126\n" +
	"\bproducts\x18\x03 \x03(\v2\x1a.ecommerce.product.ProductR\bproductsB)Z'grpc-course-protobuf/pb/ecommerce/orderb\x06proto3"

var (
	file_ecommerce_order_order_proto_rawDescOnce sync.Once
	file_ecommerce_order_order_proto_rawDescData []byte
)

func file_ecommerce_order_order_proto_rawDescGZIP() []byte {
	file_ecommerce_order_order_proto_rawDescOnce.Do(func() {
		file_ecommerce_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ecommerce_order_order_proto_rawDesc), len(file_ecommerce_order_order_proto_rawDesc)))
	})
	return file_ecommerce_order_order_proto_rawDescData
}

var file_ecommerce_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ecommerce_order_order_proto_goTypes = []any{
	(*Order)(nil),           // 0: ecommerce.order.Order
	(*product.Product)(nil), // 1: ecommerce.product.Product
}
var file_ecommerce_order_order_proto_depIdxs = []int32{
	1, // 0: ecommerce.order.Order.products:type_name -> ecommerce.product.Product
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ecommerce_order_order_proto_init() }
func file_ecommerce_order_order_proto_init() {
	if File_ecommerce_order_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ecommerce_order_order_proto_rawDesc), len(file_ecommerce_order_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ecommerce_order_order_proto_goTypes,
		DependencyIndexes: file_ecommerce_order_order_proto_depIdxs,
		MessageInfos:      file_ecommerce_order_order_proto_msgTypes,
	}.Build()
	File_ecommerce_order_order_proto = out.File
	file_ecommerce_order_order_proto_goTypes = nil
	file_ecommerce_order_order_proto_depIdxs = nil
}
